// Code generated by protoc-gen-go. DO NOT EDIT.
// source: watchpb.proto

package watchpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EventType int32

const (
	// 新增APP
	EventType_CREATE EventType = 0
	// APP的服务器地址有更新
	EventType_UPDATE EventType = 1
	// 删除APP
	EventType_DELETE EventType = 2
)

var EventType_name = map[int32]string{
	0: "CREATE",
	1: "UPDATE",
	2: "DELETE",
}

var EventType_value = map[string]int32{
	"CREATE": 0,
	"UPDATE": 1,
	"DELETE": 2,
}

func (x EventType) String() string {
	return proto.EnumName(EventType_name, int32(x))
}

func (EventType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e705afab0fb6c037, []int{0}
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_e705afab0fb6c037, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type GetAppResponse struct {
	App                  *App         `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	Servers              []*AppServer `protobuf:"bytes,2,rep,name=servers,proto3" json:"servers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetAppResponse) Reset()         { *m = GetAppResponse{} }
func (m *GetAppResponse) String() string { return proto.CompactTextString(m) }
func (*GetAppResponse) ProtoMessage()    {}
func (*GetAppResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e705afab0fb6c037, []int{1}
}

func (m *GetAppResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAppResponse.Unmarshal(m, b)
}
func (m *GetAppResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAppResponse.Marshal(b, m, deterministic)
}
func (m *GetAppResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAppResponse.Merge(m, src)
}
func (m *GetAppResponse) XXX_Size() int {
	return xxx_messageInfo_GetAppResponse.Size(m)
}
func (m *GetAppResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAppResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAppResponse proto.InternalMessageInfo

func (m *GetAppResponse) GetApp() *App {
	if m != nil {
		return m.App
	}
	return nil
}

func (m *GetAppResponse) GetServers() []*AppServer {
	if m != nil {
		return m.Servers
	}
	return nil
}

type AppServer struct {
	// IP
	Ip string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	// PORT
	Port                 string   `protobuf:"bytes,2,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppServer) Reset()         { *m = AppServer{} }
func (m *AppServer) String() string { return proto.CompactTextString(m) }
func (*AppServer) ProtoMessage()    {}
func (*AppServer) Descriptor() ([]byte, []int) {
	return fileDescriptor_e705afab0fb6c037, []int{2}
}

func (m *AppServer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppServer.Unmarshal(m, b)
}
func (m *AppServer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppServer.Marshal(b, m, deterministic)
}
func (m *AppServer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppServer.Merge(m, src)
}
func (m *AppServer) XXX_Size() int {
	return xxx_messageInfo_AppServer.Size(m)
}
func (m *AppServer) XXX_DiscardUnknown() {
	xxx_messageInfo_AppServer.DiscardUnknown(m)
}

var xxx_messageInfo_AppServer proto.InternalMessageInfo

func (m *AppServer) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *AppServer) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

type App struct {
	// 应用名称
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// 环境
	Env                  string   `protobuf:"bytes,2,opt,name=env,proto3" json:"env,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *App) Reset()         { *m = App{} }
func (m *App) String() string { return proto.CompactTextString(m) }
func (*App) ProtoMessage()    {}
func (*App) Descriptor() ([]byte, []int) {
	return fileDescriptor_e705afab0fb6c037, []int{3}
}

func (m *App) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_App.Unmarshal(m, b)
}
func (m *App) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_App.Marshal(b, m, deterministic)
}
func (m *App) XXX_Merge(src proto.Message) {
	xxx_messageInfo_App.Merge(m, src)
}
func (m *App) XXX_Size() int {
	return xxx_messageInfo_App.Size(m)
}
func (m *App) XXX_DiscardUnknown() {
	xxx_messageInfo_App.DiscardUnknown(m)
}

var xxx_messageInfo_App proto.InternalMessageInfo

func (m *App) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *App) GetEnv() string {
	if m != nil {
		return m.Env
	}
	return ""
}

type WatchCreateRequest struct {
	WatchId              string   `protobuf:"bytes,1,opt,name=watch_id,json=watchId,proto3" json:"watch_id,omitempty"`
	App                  *App     `protobuf:"bytes,2,opt,name=app,proto3" json:"app,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WatchCreateRequest) Reset()         { *m = WatchCreateRequest{} }
func (m *WatchCreateRequest) String() string { return proto.CompactTextString(m) }
func (*WatchCreateRequest) ProtoMessage()    {}
func (*WatchCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e705afab0fb6c037, []int{4}
}

func (m *WatchCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WatchCreateRequest.Unmarshal(m, b)
}
func (m *WatchCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WatchCreateRequest.Marshal(b, m, deterministic)
}
func (m *WatchCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WatchCreateRequest.Merge(m, src)
}
func (m *WatchCreateRequest) XXX_Size() int {
	return xxx_messageInfo_WatchCreateRequest.Size(m)
}
func (m *WatchCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WatchCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WatchCreateRequest proto.InternalMessageInfo

func (m *WatchCreateRequest) GetWatchId() string {
	if m != nil {
		return m.WatchId
	}
	return ""
}

func (m *WatchCreateRequest) GetApp() *App {
	if m != nil {
		return m.App
	}
	return nil
}

type WatchCancelRequest struct {
	WatchId              string   `protobuf:"bytes,1,opt,name=watch_id,json=watchId,proto3" json:"watch_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WatchCancelRequest) Reset()         { *m = WatchCancelRequest{} }
func (m *WatchCancelRequest) String() string { return proto.CompactTextString(m) }
func (*WatchCancelRequest) ProtoMessage()    {}
func (*WatchCancelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e705afab0fb6c037, []int{5}
}

func (m *WatchCancelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WatchCancelRequest.Unmarshal(m, b)
}
func (m *WatchCancelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WatchCancelRequest.Marshal(b, m, deterministic)
}
func (m *WatchCancelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WatchCancelRequest.Merge(m, src)
}
func (m *WatchCancelRequest) XXX_Size() int {
	return xxx_messageInfo_WatchCancelRequest.Size(m)
}
func (m *WatchCancelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WatchCancelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WatchCancelRequest proto.InternalMessageInfo

func (m *WatchCancelRequest) GetWatchId() string {
	if m != nil {
		return m.WatchId
	}
	return ""
}

type WatchRequest struct {
	// Types that are valid to be assigned to RequestUnion:
	//	*WatchRequest_CreateRequest
	//	*WatchRequest_CancelRequest
	RequestUnion         isWatchRequest_RequestUnion `protobuf_oneof:"request_union"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *WatchRequest) Reset()         { *m = WatchRequest{} }
func (m *WatchRequest) String() string { return proto.CompactTextString(m) }
func (*WatchRequest) ProtoMessage()    {}
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e705afab0fb6c037, []int{6}
}

func (m *WatchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WatchRequest.Unmarshal(m, b)
}
func (m *WatchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WatchRequest.Marshal(b, m, deterministic)
}
func (m *WatchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WatchRequest.Merge(m, src)
}
func (m *WatchRequest) XXX_Size() int {
	return xxx_messageInfo_WatchRequest.Size(m)
}
func (m *WatchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WatchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WatchRequest proto.InternalMessageInfo

type isWatchRequest_RequestUnion interface {
	isWatchRequest_RequestUnion()
}

type WatchRequest_CreateRequest struct {
	CreateRequest *WatchCreateRequest `protobuf:"bytes,1,opt,name=create_request,json=createRequest,proto3,oneof"`
}

type WatchRequest_CancelRequest struct {
	CancelRequest *WatchCancelRequest `protobuf:"bytes,2,opt,name=cancel_request,json=cancelRequest,proto3,oneof"`
}

func (*WatchRequest_CreateRequest) isWatchRequest_RequestUnion() {}

func (*WatchRequest_CancelRequest) isWatchRequest_RequestUnion() {}

func (m *WatchRequest) GetRequestUnion() isWatchRequest_RequestUnion {
	if m != nil {
		return m.RequestUnion
	}
	return nil
}

func (m *WatchRequest) GetCreateRequest() *WatchCreateRequest {
	if x, ok := m.GetRequestUnion().(*WatchRequest_CreateRequest); ok {
		return x.CreateRequest
	}
	return nil
}

func (m *WatchRequest) GetCancelRequest() *WatchCancelRequest {
	if x, ok := m.GetRequestUnion().(*WatchRequest_CancelRequest); ok {
		return x.CancelRequest
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*WatchRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*WatchRequest_CreateRequest)(nil),
		(*WatchRequest_CancelRequest)(nil),
	}
}

type WatchResponse struct {
	Event EventType `protobuf:"varint,1,opt,name=event,proto3,enum=watchpb.EventType" json:"event,omitempty"`
	App   *App      `protobuf:"bytes,2,opt,name=app,proto3" json:"app,omitempty"`
	// 用于服务端标记连接的创建成功
	Created bool `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"`
	// 用于服务端收到客户端取消连接的信号，并处理成功后的返回
	Canceled bool `protobuf:"varint,4,opt,name=canceled,proto3" json:"canceled,omitempty"`
	// cancel_reason indicates the reason for canceling the watcher.
	CancelReason         string       `protobuf:"bytes,5,opt,name=cancel_reason,json=cancelReason,proto3" json:"cancel_reason,omitempty"`
	Servers              []*AppServer `protobuf:"bytes,6,rep,name=servers,proto3" json:"servers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *WatchResponse) Reset()         { *m = WatchResponse{} }
func (m *WatchResponse) String() string { return proto.CompactTextString(m) }
func (*WatchResponse) ProtoMessage()    {}
func (*WatchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e705afab0fb6c037, []int{7}
}

func (m *WatchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WatchResponse.Unmarshal(m, b)
}
func (m *WatchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WatchResponse.Marshal(b, m, deterministic)
}
func (m *WatchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WatchResponse.Merge(m, src)
}
func (m *WatchResponse) XXX_Size() int {
	return xxx_messageInfo_WatchResponse.Size(m)
}
func (m *WatchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WatchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WatchResponse proto.InternalMessageInfo

func (m *WatchResponse) GetEvent() EventType {
	if m != nil {
		return m.Event
	}
	return EventType_CREATE
}

func (m *WatchResponse) GetApp() *App {
	if m != nil {
		return m.App
	}
	return nil
}

func (m *WatchResponse) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func (m *WatchResponse) GetCanceled() bool {
	if m != nil {
		return m.Canceled
	}
	return false
}

func (m *WatchResponse) GetCancelReason() string {
	if m != nil {
		return m.CancelReason
	}
	return ""
}

func (m *WatchResponse) GetServers() []*AppServer {
	if m != nil {
		return m.Servers
	}
	return nil
}

func init() {
	proto.RegisterEnum("watchpb.EventType", EventType_name, EventType_value)
	proto.RegisterType((*Empty)(nil), "watchpb.Empty")
	proto.RegisterType((*GetAppResponse)(nil), "watchpb.GetAppResponse")
	proto.RegisterType((*AppServer)(nil), "watchpb.AppServer")
	proto.RegisterType((*App)(nil), "watchpb.App")
	proto.RegisterType((*WatchCreateRequest)(nil), "watchpb.WatchCreateRequest")
	proto.RegisterType((*WatchCancelRequest)(nil), "watchpb.WatchCancelRequest")
	proto.RegisterType((*WatchRequest)(nil), "watchpb.WatchRequest")
	proto.RegisterType((*WatchResponse)(nil), "watchpb.WatchResponse")
}

func init() { proto.RegisterFile("watchpb.proto", fileDescriptor_e705afab0fb6c037) }

var fileDescriptor_e705afab0fb6c037 = []byte{
	// 446 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0x5d, 0x8b, 0xd3, 0x40,
	0x14, 0xdd, 0x49, 0xb6, 0x5f, 0x77, 0x9b, 0x5a, 0x2e, 0xa8, 0xb1, 0x82, 0x94, 0xf1, 0x25, 0xa8,
	0x6c, 0xa5, 0x82, 0x0f, 0xbe, 0xd5, 0x36, 0xa8, 0x20, 0xb8, 0x8c, 0x15, 0xdf, 0x2c, 0xd9, 0xe4,
	0x82, 0x01, 0x77, 0x32, 0x26, 0xd9, 0xca, 0xbe, 0xf8, 0x87, 0xfc, 0x57, 0xfe, 0x12, 0x99, 0x8f,
	0x84, 0x74, 0x55, 0xfa, 0x76, 0x3f, 0xce, 0x3d, 0x39, 0xe7, 0xde, 0x0c, 0x04, 0x3f, 0x92, 0x3a,
	0xfd, 0xaa, 0x2e, 0xcf, 0x55, 0x59, 0xd4, 0x05, 0x0e, 0x5c, 0xca, 0x07, 0xd0, 0x8b, 0xaf, 0x54,
	0x7d, 0xc3, 0xbf, 0xc0, 0xe4, 0x0d, 0xd5, 0x2b, 0xa5, 0x04, 0x55, 0xaa, 0x90, 0x15, 0xe1, 0x23,
	0xf0, 0x13, 0xa5, 0x42, 0x36, 0x67, 0xd1, 0xd9, 0x72, 0x7c, 0xde, 0x10, 0x68, 0x88, 0x6e, 0xe0,
	0x33, 0x18, 0x54, 0x54, 0xee, 0xa9, 0xac, 0x42, 0x6f, 0xee, 0x47, 0x67, 0x4b, 0xec, 0x62, 0x3e,
	0x9a, 0x96, 0x68, 0x20, 0x7c, 0x01, 0xa3, 0xb6, 0x8a, 0x13, 0xf0, 0x72, 0xcb, 0x3c, 0x12, 0x5e,
	0xae, 0x10, 0xe1, 0x54, 0x15, 0x65, 0x1d, 0x7a, 0xa6, 0x62, 0x62, 0xfe, 0x14, 0xfc, 0x95, 0x32,
	0x2d, 0x99, 0x5c, 0x91, 0x03, 0x9b, 0x18, 0xa7, 0xe0, 0x93, 0xdc, 0x3b, 0xb4, 0x0e, 0xf9, 0x07,
	0xc0, 0xcf, 0xfa, 0xdb, 0xeb, 0x92, 0x92, 0x9a, 0x04, 0x7d, 0xbf, 0xa6, 0xaa, 0xc6, 0x07, 0x30,
	0x34, 0x8a, 0x76, 0x79, 0xe6, 0xe6, 0xad, 0xef, 0x77, 0x59, 0x63, 0xce, 0xfb, 0x8f, 0x39, 0xbe,
	0x68, 0x08, 0x13, 0x99, 0xd2, 0xb7, 0xe3, 0x84, 0xfc, 0x17, 0x83, 0xb1, 0x99, 0x68, 0xb0, 0x1b,
	0x98, 0xa4, 0x46, 0xcd, 0xae, 0xb4, 0x15, 0xb7, 0xc9, 0x87, 0xed, 0xc7, 0xfe, 0x56, 0xfc, 0xf6,
	0x44, 0x04, 0xe9, 0x81, 0x05, 0xcd, 0x62, 0x24, 0xb4, 0x2c, 0xde, 0x3f, 0x59, 0xba, 0x32, 0x0d,
	0x4b, 0xb7, 0xf0, 0xfa, 0x0e, 0x04, 0x6e, 0x7c, 0x77, 0x2d, 0xf3, 0x42, 0xf2, 0xdf, 0x0c, 0x02,
	0xa7, 0xd6, 0x5d, 0x3b, 0x82, 0x1e, 0xed, 0x49, 0x5a, 0x95, 0x93, 0xce, 0x2d, 0x63, 0x5d, 0xdd,
	0xde, 0x28, 0x12, 0x16, 0x70, 0x6c, 0x75, 0x18, 0xc2, 0xc0, 0x7a, 0xc8, 0x42, 0x7f, 0xce, 0xa2,
	0xa1, 0x68, 0x52, 0x9c, 0xc1, 0xd0, 0xea, 0xa2, 0x2c, 0x3c, 0x35, 0xad, 0x36, 0xc7, 0xc7, 0x10,
	0xb4, 0x46, 0x93, 0xaa, 0x90, 0x61, 0xcf, 0xec, 0x77, 0xdc, 0x18, 0xd1, 0xb5, 0xee, 0x2f, 0xd7,
	0x3f, 0xfa, 0xcb, 0x3d, 0x59, 0xc0, 0xa8, 0x15, 0x8f, 0x00, 0xfd, 0xb5, 0x88, 0x57, 0xdb, 0x78,
	0x7a, 0xa2, 0xe3, 0x4f, 0x17, 0x1b, 0x1d, 0x33, 0x1d, 0x6f, 0xe2, 0xf7, 0xf1, 0x36, 0x9e, 0x7a,
	0xcb, 0x9f, 0x30, 0xb4, 0x4b, 0xb9, 0x58, 0xe3, 0x4b, 0x08, 0xec, 0x7b, 0xb0, 0xac, 0x15, 0x1e,
	0x38, 0x9d, 0xdd, 0x6f, 0xb3, 0x5b, 0xaf, 0xe6, 0x15, 0xf4, 0x0c, 0x07, 0xde, 0x3d, 0xbc, 0x90,
	0x3b, 0xc5, 0xec, 0xde, 0xed, 0xb2, 0x9d, 0x8b, 0xd8, 0x73, 0x76, 0xd9, 0x37, 0x8f, 0xf3, 0xc5,
	0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc0, 0x87, 0x64, 0xe2, 0xad, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WatchRPCClient is the client API for WatchRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WatchRPCClient interface {
	// 获取app的服务器地址
	GetAppServers(ctx context.Context, in *App, opts ...grpc.CallOption) (*GetAppResponse, error)
	// 推送app服务器地址的变化情况
	Watch(ctx context.Context, opts ...grpc.CallOption) (WatchRPC_WatchClient, error)
}

type watchRPCClient struct {
	cc *grpc.ClientConn
}

func NewWatchRPCClient(cc *grpc.ClientConn) WatchRPCClient {
	return &watchRPCClient{cc}
}

func (c *watchRPCClient) GetAppServers(ctx context.Context, in *App, opts ...grpc.CallOption) (*GetAppResponse, error) {
	out := new(GetAppResponse)
	err := c.cc.Invoke(ctx, "/watchpb.WatchRPC/GetAppServers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *watchRPCClient) Watch(ctx context.Context, opts ...grpc.CallOption) (WatchRPC_WatchClient, error) {
	stream, err := c.cc.NewStream(ctx, &_WatchRPC_serviceDesc.Streams[0], "/watchpb.WatchRPC/Watch", opts...)
	if err != nil {
		return nil, err
	}
	x := &watchRPCWatchClient{stream}
	return x, nil
}

type WatchRPC_WatchClient interface {
	Send(*WatchRequest) error
	Recv() (*WatchResponse, error)
	grpc.ClientStream
}

type watchRPCWatchClient struct {
	grpc.ClientStream
}

func (x *watchRPCWatchClient) Send(m *WatchRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *watchRPCWatchClient) Recv() (*WatchResponse, error) {
	m := new(WatchResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// WatchRPCServer is the server API for WatchRPC service.
type WatchRPCServer interface {
	// 获取app的服务器地址
	GetAppServers(context.Context, *App) (*GetAppResponse, error)
	// 推送app服务器地址的变化情况
	Watch(WatchRPC_WatchServer) error
}

// UnimplementedWatchRPCServer can be embedded to have forward compatible implementations.
type UnimplementedWatchRPCServer struct {
}

func (*UnimplementedWatchRPCServer) GetAppServers(ctx context.Context, req *App) (*GetAppResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAppServers not implemented")
}
func (*UnimplementedWatchRPCServer) Watch(srv WatchRPC_WatchServer) error {
	return status.Errorf(codes.Unimplemented, "method Watch not implemented")
}

func RegisterWatchRPCServer(s *grpc.Server, srv WatchRPCServer) {
	s.RegisterService(&_WatchRPC_serviceDesc, srv)
}

func _WatchRPC_GetAppServers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(App)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatchRPCServer).GetAppServers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/watchpb.WatchRPC/GetAppServers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatchRPCServer).GetAppServers(ctx, req.(*App))
	}
	return interceptor(ctx, in, info, handler)
}

func _WatchRPC_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WatchRPCServer).Watch(&watchRPCWatchServer{stream})
}

type WatchRPC_WatchServer interface {
	Send(*WatchResponse) error
	Recv() (*WatchRequest, error)
	grpc.ServerStream
}

type watchRPCWatchServer struct {
	grpc.ServerStream
}

func (x *watchRPCWatchServer) Send(m *WatchResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *watchRPCWatchServer) Recv() (*WatchRequest, error) {
	m := new(WatchRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _WatchRPC_serviceDesc = grpc.ServiceDesc{
	ServiceName: "watchpb.WatchRPC",
	HandlerType: (*WatchRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAppServers",
			Handler:    _WatchRPC_GetAppServers_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _WatchRPC_Watch_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "watchpb.proto",
}
